version: "2.4"

services:
  frontend:
    container_name: frontend
    ports:
      - 3000:3000
    build: 
        context: frontend/
        args: 
            BACKEND_ADDRESS: ${BACKEND_ADDRESS}
    volumes:
      - modules:/usr/src/app/node_modules
      - next:/usr/src/app/.next
  backend:
    container_name: backend
    build: backend/
    ports:
    - 8081:8081
    environment:
      - ES_INDEX=${ES_INDEX}
      - OPAL_ELASTICSEARCH_URL=${OPAL_ELASTICSEARCH_URL}
      - OPAL_ELASTICSEARCH_PORT=${OPAL_ELASTICSEARCH_PORT}

volumes:
  modules:
  next:
